/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Multicall } from "./Multicall";
export type { Multicall2 } from "./Multicall2";
export type { WeatherRecord } from "./WeatherRecord";
