/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CronosOracle } from "./CronosOracle";
export type { ERC20 } from "./ERC20";
export type { Multicall } from "./Multicall";
export type { Multicall2 } from "./Multicall2";
export type { WeatherRecord } from "./WeatherRecord";
