/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface WeatherRecordInterface extends utils.Interface {
  functions: {
    "getWeather(uint32,bytes32)": FunctionFragment;
    "reportWeather(uint32,bytes32,uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getWeather" | "reportWeather"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getWeather",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reportWeather",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getWeather", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reportWeather",
    data: BytesLike
  ): Result;

  events: {};
}

export interface WeatherRecord extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WeatherRecordInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      overrides?: CallOverrides
    ): Promise<[number]>;

    reportWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      temperature: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getWeather(
    batchId: BigNumberish,
    cityName: BytesLike,
    overrides?: CallOverrides
  ): Promise<number>;

  reportWeather(
    batchId: BigNumberish,
    cityName: BytesLike,
    temperature: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      overrides?: CallOverrides
    ): Promise<number>;

    reportWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      temperature: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reportWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      temperature: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reportWeather(
      batchId: BigNumberish,
      cityName: BytesLike,
      temperature: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
