/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  WeatherRecord,
  WeatherRecordInterface,
} from "../../abis/WeatherRecord";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "batchId",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "cityName",
        type: "bytes32",
      },
    ],
    name: "getWeather",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "batchId",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "cityName",
        type: "bytes32",
      },
      {
        internalType: "uint32",
        name: "temperature",
        type: "uint32",
      },
    ],
    name: "reportWeather",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class WeatherRecord__factory {
  static readonly abi = _abi;
  static createInterface(): WeatherRecordInterface {
    return new utils.Interface(_abi) as WeatherRecordInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WeatherRecord {
    return new Contract(address, _abi, signerOrProvider) as WeatherRecord;
  }
}
