/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as abis from "./abis";
export type { abis };
import type * as artifacts from "./artifacts";
export type { artifacts };
export * as factories from "./factories";
export type { Multicall } from "./artifacts/contracts/Multicall";
export { Multicall__factory } from "./factories/artifacts/contracts/Multicall__factory";
export type { Multicall2 } from "./artifacts/contracts/Multicall2";
export { Multicall2__factory } from "./factories/artifacts/contracts/Multicall2__factory";
export type { WeatherRecord } from "./artifacts/contracts/WeatherRecord";
export { WeatherRecord__factory } from "./factories/artifacts/contracts/WeatherRecord__factory";
export type { CronosOracle } from "./abis/CronosOracle";
export { CronosOracle__factory } from "./factories/abis/CronosOracle__factory";
export type { ERC20 } from "./abis/ERC20";
export { ERC20__factory } from "./factories/abis/ERC20__factory";
